version: '3'

includes:
  build: scripts/build.taskfile.yml
  test: scripts/test.taskfile.yml
  run: scripts/run.taskfile.yml
  docker: scripts/docker.taskfile.yml
  k8s: scripts/k8s.taskfile.yml
  doc: scripts/doc.taskfile.yml
  www: scripts/www.taskfile.yml

tasks:
  default:
    desc: "Print help"
    cmds:
      - task -a

  release:
    desc: "Update version number"
    cmds:
      - echo {{.CLI_ARGS}} > VERSION.txt
      - yq eval '.version = "{{.CLI_ARGS}}"' -i k8s/charts/flowg/Chart.yaml
      - yq eval '.appVersion = "{{.CLI_ARGS}}"' -i k8s/charts/flowg/Chart.yaml
