---
name: deploy-website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@scm
        uses: actions/checkout@v4

      - name: setup@go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: setup@node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: setup@rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: setup@task
        uses: arduino/setup-task@v2

      - name: gen@clidoc
        run: task build doc

      - name: build@website
        working-directory: ./website
        run: |
          npm i
          npm run build

      - name: upload@artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy@pages
        id: deployment
        uses: actions/deploy-pages@v4
